name: rickandmortyproject
description: "Listagem de personagens da Série Rick and Morty e exibição de detalhes do personagem selecionado."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  image_path: "assets/icons/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/images/